apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  #namespace: prod
spec:
  containers:
  - name: httpd
    image: httpd
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  #nodeSelector:
    #making: "test"
