---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-pass
data:
  MY_SQL_PASSWORD: admin
  TIMING: admin
...
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb
    volumeMounts:
      - mountPath: /var/lib/mysql 
        name: mariadb
    envFrom:
      - configMapRef:
        name: mysql-pass
   volumes:
    - name: mariadb
      awsElasticBlockStore:
        volumeID: vol-0fd134f6f2951ef4f
        fsType: ext4
  nodeSelector:
          making: "test"
...

