---
kind: Secret
apiVersion: v1
data: 
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyRmphR1YwTVRrNU5EbzVNemN3TWpNMk9UZzAiCgkJfQoJfQp9 
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
...
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: httpd
    image: kubectl
  imagePullSecrets:
  - name: cred
...
