kind: Secret
apiVersion: v1
data: 
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImMyRmphR1YwTVRrNU5Eb3hNak0wTlhOVCIKCQl9Cgl9Cn0=
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
