---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checking
data:
  NAME: Raghu
  TIMING: 10AM
...

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: httpd
    image: sachet1994/httpd:v1
    env:
    - name: NAME 
      valueFrom:
          configMapKeyRef:
            name: checking #configmap name
            key: NAME #name of the date
    - name: Anything #displayed when we check using exec
      valueFrom:
          configMapKeyRef:
            name: checking
            key: TIMING
    - name: TIMING
      valueFrom:
          configMapKeyRef:
            name: checking
            key: TIMING
...
