---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checking
data:
  env: prod
...

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: httpd
    image: sachet1994/httpd:v1
    env:
    - name: env 
      valueFrom:
          configMapKeyRef:
            name: checking
            key: env
...
