---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checking
data:
  NAME: Raghu
...

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: httpd
    image: sachet1994/httpd:v1
    env:
    - name: NAME 
      valueFrom:
          configMapKeyRef:
            name: checking
...
