apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: httpd
    image: sachet1994/httpd:v1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
nodeSelector: ip-192-168-68-105.us-east-2.compute.internal
