apiVersion: v1
kind: Pod
metadata:
  name: mariadb-client
spec:
  containers:
  - name: centos
    image: centos
    command: ["sleep","100000"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
