apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  #namespace: prod
spec:
  containers:
  - name: httpd
    image: mariadb
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "env"
            operator: "Equal" #In
            values:
            - prd
            -preprd
