apiVersion: v1
kind: Pod
metadata:
  name: myapp1
  #namespace: prod
spec:
  containers:
  - name: httpd
    image: mariadb
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  tolerations:
    key: "checking"
    value: "testing"
    effect: "NoSchedule"
    operator: "Equal"
